# Generated by Django 6.0 on 2026-07-08 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='kharid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('discribshen', models.TextField()),
                ('image', models.ImageField(upload_to='images/kharid')),
                ('gheymat', models.DecimalField(decimal_places=0, max_digits=15)),
            ],
        ),
    ]
