# Generated by Django 6.0 on 2026-07-09 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contect_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='replied_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='تاریخ پاسخ'),
        ),
        migrations.AddField(
            model_name='comment',
            name='reply',
            field=models.TextField(blank=True, null=True, verbose_name='پاسخ ادمین'),
        ),
    ]
