# Generated by Django 6.0 on 2026-07-05 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='acstori',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titile', models.CharField(max_length=30)),
                ('discribshen', models.TextField(max_length=20)),
                ('img', models.ImageField(upload_to='image/acstori')),
                ('ghymat', models.DecimalField(decimal_places=0, max_digits=15)),
            ],
        ),
    ]
