# Generated by Django 6.0 on 2026-07-05 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acastori_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='acstori',
            old_name='ghymat',
            new_name='gheymat',
        ),
        migrations.RenameField(
            model_name='acstori',
            old_name='img',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='acstori',
            old_name='titile',
            new_name='title',
        ),
        migrations.AlterField(
            model_name='acstori',
            name='discribshen',
            field=models.TextField(),
        ),
    ]
