# Generated by Django 6.0 on 2026-07-03 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_app', '0002_alter_shop_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='category',
            field=models.CharField(choices=[('general', 'General'), ('nike', 'Nike')], default='general', max_length=20),
        ),
    ]
