# Generated by Django 6.0 on 2026-07-08 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_app', '0003_shop_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='likes',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
