# Generated by Django 6.0 on 2026-07-26 20:00

from django.db import migrations, models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop_app', '0004_shop_likes'),
    ]

operations = [
    migrations.AddField(
        model_name='shop',
        name='discribshen',
        field=models.TextField(default=''),
    ),
]
