# Generated by Django 6.0 on 2026-07-07 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='dis',
            field=models.TextField(default=1, max_length={}),
            preserve_default=False,
        ),
    ]
